---
title: "Team Project: Data Analysis Project Proposal: Consumer Attractions On Social Network Era"
author: "Jianye Han (jianyeh2), Zach Litz (zlitz2), Megan Masanz (mjneuman)"
date: "July 14, 2017"
output: html_document
---
### Introduction
This document is the data analysis project proposal for the STAT 420 team project. The following sections will fully describe the project proposal and all other required information.

### Team Members
- Jianye Han (NetID jianyeh2)
- Zach Litz (NetID zlitz2)
- Megan Masanz (NetID mjneuman)

### Project Title
This project is tentatively named **Linear Regression analysis of Consumer Attractions On Social Network Era**

### Statement of Interest
While no one in our group has a direct business, science, or research interest in this data, collectively there is acknowledgement that social media has had a drastic impact on today's digital marketing.  

Facebook's mission is: 

[Founded in 2004, Facebook's mission is to give people the power to build community and bring the world closer together. People use Facebook to stay connected with friends and family, to discover what's going on in the world, and to share and express what matters to them.](https://newsroom.fb.com/company-info/)

Note that Facebook does not include marketing revenue in their mission statement, but according to their [`2016 Annual Report`](http://d18rn0p25nwr6d.cloudfront.net/CIK-0001326801/80a179c9-2dea-49a7-a710-2f3e0f45663a.pdf) **"We generate substantially all of our revenue from advertising."**

Further Facebook makes the claim [Your people are here](https://www.facebook.com/business/products/ads) due to their [statistics](https://newsroom.fb.com/company-info/) of:


- 1.28 billion daily active users on average for March 2017
- 1.94 billion monthly active users as of March 31, 2017


Facebook's dependency on advertising revenue and their reach into billions of people's lives, make analyzing data from a company purchasing ads with Facebook an interesting area to gain understanding, as this information is not only important to the companies that are paying for these services, but they are key to the health of Facebook as a company.  

Given this interest, we will be exploring a dataset found at [UIC's Machine Learning Repository](http://archive.ics.uci.edu/ml/datasets/Facebook+metrics), which has been included [`dataset_Facebook.csv`](dataset_Facebook.csv) alternatively a project .zip file can be downloaded from [here](http://archive.ics.uci.edu/ml/machine-learning-databases/00368/Facebook_metrics.zip) containing a representative data set that collected published posts of a Facebook page of a worldwide renowned cosmetic brand.


### Exploration
When examining this data, we recall

"Marketers pay for ad products either directly or through their relationships with advertising agencies, based on **the number of clicks made by people, the number of actions taken by people, or the number of impressions delivered.** We recognize revenue from the delivery of click-based ads in the period in which a person clicks on the content, and action-based ads in the period in which a person takes the action the marketer contracted for." (http://d18rn0p25nwr6d.cloudfront.net/CIK-0001326801/80a179c9-2dea-49a7-a710-2f3e0f45663a.pdf)

We considered that "The number of people who clicked anywhere in a post (Lifetime.post.consumers)" are potential consumers of the product. We would like to explore what other variable (e.g. Total page likes) would predict or have correlations with this response variable.


### Description of the dataset

This dataset contains a total of 500 records. A cursory analysis found at least one record with missing data which will be removed from the data. There is a potential that more records will be removed during the initial analysis and cleaning portion of the project, but overall we expect to be able to use nearly all 500 records in our analysis.


This data contains records obtained between the 1st of January and the 31st of December of 2014. 


#### Potential Response Variable 
* `Lifetime Post Consumers`:  The number of people who clicked anywhere in a post.


This will be our initial focus of analysis, but it may change as we progress with the project and explore other relationships. This is because the data contains other variables that may be better predictors for determining potential consumers. 

#### Potential Predictor Variables 
* `Lifetime Post Total Reach`:  The number of people who saw a page post (unique users).

* `Lifetime Post Total Impressions`:  Impressions are the number of times a post from a page is displayed, whether the post is clicked or not. People may see multiple impressions of the same post. For example, someone might see a Page update in News Feed once, and then a second time if a friend shares it.

* `Lifetime Engaged Users`:  The number of people who clicked anywhere in a post (unique users).

* `Lifetime Post Consumptions`:  The number of clicks anywhere in a post.

* `Lifetime Post Impressions by people who have liked your Page`:  Total number of impressions just from people who have liked a page.

* `Lifetime Post reach by people who like your Page`:  The number of people who saw a page post because they have liked that page (unique users).

* `Lifetime People who have liked your Page and engaged with your post`:  The number of people who have liked a Page and clicked anywhere in a post (Unique users). 

* `comment` :  Number of comments on the publication. 

* `like`:  Number of "Likes" on the publication.

* `share`:  Number of times the publication was shared. 

* `Total Interactions`:  The sum of "likes,""comments," and "shares" of the post.

* `Type`:  Type of content.  Factor variable with levels including: "Link"   "Photo"  "Status" "Video".

(Some descriptions refer to: https://www.facebook.com/help/274400362581037)


#### R Example
The below code block shows the data being loaded in to R with some sample output to prove the data was successfully loaded.
```{r, fig.height=50, fig.width=50}
fb = read.table("dataset_Facebook.csv", sep = ";", header = T)
head(fb[,11])
```



# REFERENCES

Our chosen dataset was found on the [UCI Machine Learning Repository](http://archive.ics.uci.edu/ml/datasets/Facebook+metrics).

The data originates from 

> (Moro et al., 2016) Moro, S., Rita, P., & Vala, B. (2016). Predicting social media performance metrics and evaluation of the impact on brand building: A data mining approach. Journal of Business Research, 69(9), 3341-3351.

The above paper can be found for purchase [here](http://www.sciencedirect.com/science/article/pii/S0148296316000813?via%3Dihub) and has also been included [Research.pdf](Research.pdf).

This data is publicly available for research purposes.



